export const typographyFont: string;
export const container: string;
export const leftContainer: string;
export const rightContainer: string;
export const item: string;
export const icon: string;
export const syncedIcon: string;
export const dexterIcon: string;
export const text: string;
