export const panelBgColor: string;
export const typographyFont: string;
export const fixedLayer: string;
export const appear: string;
export const closed: string;
export const disappear: string;
export const container: string;
export const big: string;
export const fluid: string;
