export const typographyFont: string;
export const anchor: string;
export const item: string;
export const highlight: string;
export const disabled: string;
export const appear: string;
export const icon: string;
export const key: string;
export const label: string;
