// flow-typed signature: 457c82c05c5c3b2df4f3cd8e3baa6900
// flow-typed version: <<STUB>>/electron-prebuilt_v^1.4.13/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-prebuilt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-prebuilt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-prebuilt/cli' {
  declare module.exports: any;
}

declare module 'electron-prebuilt/install' {
  declare module.exports: any;
}

declare module 'electron-prebuilt/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-prebuilt/cli.js' {
  declare module.exports: $Exports<'electron-prebuilt/cli'>;
}
declare module 'electron-prebuilt/index' {
  declare module.exports: $Exports<'electron-prebuilt'>;
}
declare module 'electron-prebuilt/index.js' {
  declare module.exports: $Exports<'electron-prebuilt'>;
}
declare module 'electron-prebuilt/install.js' {
  declare module.exports: $Exports<'electron-prebuilt/install'>;
}
declare module 'electron-prebuilt/test/index.js' {
  declare module.exports: $Exports<'electron-prebuilt/test/index'>;
}
