// flow-typed signature: e7d6bb71faf8b985555b8232877bc7b8
// flow-typed version: <<STUB>>/exec-loader_v^3.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exec-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exec-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exec-loader/index' {
  declare module.exports: $Exports<'exec-loader'>;
}
declare module 'exec-loader/index.js' {
  declare module.exports: $Exports<'exec-loader'>;
}
