// flow-typed signature: 7e43f61198c92cb940b1312819704944
// flow-typed version: <<STUB>>/mock-fs_v^4.4.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-fs/benchmarks/read-integration-mock' {
  declare module.exports: any;
}

declare module 'mock-fs/benchmarks/read-integration-real' {
  declare module.exports: any;
}

declare module 'mock-fs/benchmarks/read-mock' {
  declare module.exports: any;
}

declare module 'mock-fs/benchmarks/read-real' {
  declare module.exports: any;
}

declare module 'mock-fs/benchmarks/write-integration-mock' {
  declare module.exports: any;
}

declare module 'mock-fs/benchmarks/write-integration-real' {
  declare module.exports: any;
}

declare module 'mock-fs/benchmarks/write-mock' {
  declare module.exports: any;
}

declare module 'mock-fs/benchmarks/write-real' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/binding' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/descriptor' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/directory' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/error' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/file' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/filesystem' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/index' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/item' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/symlink' {
  declare module.exports: any;
}

declare module 'mock-fs/test/helper' {
  declare module.exports: any;
}

declare module 'mock-fs/test/integration/filecount' {
  declare module.exports: any;
}

declare module 'mock-fs/test/integration/filecount.spec' {
  declare module.exports: any;
}

declare module 'mock-fs/test/lib/binding.spec' {
  declare module.exports: any;
}

declare module 'mock-fs/test/lib/descriptor.spec' {
  declare module.exports: any;
}

declare module 'mock-fs/test/lib/directory.spec' {
  declare module.exports: any;
}

declare module 'mock-fs/test/lib/file.spec' {
  declare module.exports: any;
}

declare module 'mock-fs/test/lib/filesystem.spec' {
  declare module.exports: any;
}

declare module 'mock-fs/test/lib/index.spec' {
  declare module.exports: any;
}

declare module 'mock-fs/test/lib/item.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-fs/benchmarks/read-integration-mock.js' {
  declare module.exports: $Exports<'mock-fs/benchmarks/read-integration-mock'>;
}
declare module 'mock-fs/benchmarks/read-integration-real.js' {
  declare module.exports: $Exports<'mock-fs/benchmarks/read-integration-real'>;
}
declare module 'mock-fs/benchmarks/read-mock.js' {
  declare module.exports: $Exports<'mock-fs/benchmarks/read-mock'>;
}
declare module 'mock-fs/benchmarks/read-real.js' {
  declare module.exports: $Exports<'mock-fs/benchmarks/read-real'>;
}
declare module 'mock-fs/benchmarks/write-integration-mock.js' {
  declare module.exports: $Exports<'mock-fs/benchmarks/write-integration-mock'>;
}
declare module 'mock-fs/benchmarks/write-integration-real.js' {
  declare module.exports: $Exports<'mock-fs/benchmarks/write-integration-real'>;
}
declare module 'mock-fs/benchmarks/write-mock.js' {
  declare module.exports: $Exports<'mock-fs/benchmarks/write-mock'>;
}
declare module 'mock-fs/benchmarks/write-real.js' {
  declare module.exports: $Exports<'mock-fs/benchmarks/write-real'>;
}
declare module 'mock-fs/lib/binding.js' {
  declare module.exports: $Exports<'mock-fs/lib/binding'>;
}
declare module 'mock-fs/lib/descriptor.js' {
  declare module.exports: $Exports<'mock-fs/lib/descriptor'>;
}
declare module 'mock-fs/lib/directory.js' {
  declare module.exports: $Exports<'mock-fs/lib/directory'>;
}
declare module 'mock-fs/lib/error.js' {
  declare module.exports: $Exports<'mock-fs/lib/error'>;
}
declare module 'mock-fs/lib/file.js' {
  declare module.exports: $Exports<'mock-fs/lib/file'>;
}
declare module 'mock-fs/lib/filesystem.js' {
  declare module.exports: $Exports<'mock-fs/lib/filesystem'>;
}
declare module 'mock-fs/lib/index.js' {
  declare module.exports: $Exports<'mock-fs/lib/index'>;
}
declare module 'mock-fs/lib/item.js' {
  declare module.exports: $Exports<'mock-fs/lib/item'>;
}
declare module 'mock-fs/lib/symlink.js' {
  declare module.exports: $Exports<'mock-fs/lib/symlink'>;
}
declare module 'mock-fs/test/helper.js' {
  declare module.exports: $Exports<'mock-fs/test/helper'>;
}
declare module 'mock-fs/test/integration/filecount.js' {
  declare module.exports: $Exports<'mock-fs/test/integration/filecount'>;
}
declare module 'mock-fs/test/integration/filecount.spec.js' {
  declare module.exports: $Exports<'mock-fs/test/integration/filecount.spec'>;
}
declare module 'mock-fs/test/lib/binding.spec.js' {
  declare module.exports: $Exports<'mock-fs/test/lib/binding.spec'>;
}
declare module 'mock-fs/test/lib/descriptor.spec.js' {
  declare module.exports: $Exports<'mock-fs/test/lib/descriptor.spec'>;
}
declare module 'mock-fs/test/lib/directory.spec.js' {
  declare module.exports: $Exports<'mock-fs/test/lib/directory.spec'>;
}
declare module 'mock-fs/test/lib/file.spec.js' {
  declare module.exports: $Exports<'mock-fs/test/lib/file.spec'>;
}
declare module 'mock-fs/test/lib/filesystem.spec.js' {
  declare module.exports: $Exports<'mock-fs/test/lib/filesystem.spec'>;
}
declare module 'mock-fs/test/lib/index.spec.js' {
  declare module.exports: $Exports<'mock-fs/test/lib/index.spec'>;
}
declare module 'mock-fs/test/lib/item.spec.js' {
  declare module.exports: $Exports<'mock-fs/test/lib/item.spec'>;
}
