// flow-typed signature: 52ebe2abb14dcd879941aa995a2aa70b
// flow-typed version: <<STUB>>/postcss-short_v^4.1.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-short'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-short' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-short/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-short/example.js' {
  declare module.exports: $Exports<'postcss-short/example'>;
}
declare module 'postcss-short/index' {
  declare module.exports: $Exports<'postcss-short'>;
}
declare module 'postcss-short/index.js' {
  declare module.exports: $Exports<'postcss-short'>;
}
