// flow-typed signature: 5154edfcd087dbe1185664777d718e1e
// flow-typed version: <<STUB>>/redux-saga_v^0.15.5/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga/dist/redux-saga' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga.min' {
  declare module.exports: any;
}

declare module 'redux-saga/es/effects' {
  declare module.exports: any;
}

declare module 'redux-saga/es/index' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/buffers' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/channel' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/io' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/proc' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/runSaga' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/sagaHelpers/fsmIterator' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/sagaHelpers/index' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/sagaHelpers/takeEvery' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/sagaHelpers/takeLatest' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/sagaHelpers/throttle' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/scheduler' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/es/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/effects' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/index' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/buffers' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/channel' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/io' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/proc' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/runSaga' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/sagaHelpers/fsmIterator' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/sagaHelpers/index' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/sagaHelpers/takeEvery' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/sagaHelpers/takeLatest' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/sagaHelpers/throttle' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/scheduler' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/rollup.config' {
  declare module.exports: any;
}

declare module 'redux-saga/src/effects' {
  declare module.exports: any;
}

declare module 'redux-saga/src/index' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/buffers' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/channel' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/io' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/proc' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/runSaga' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/sagaHelpers/fsmIterator' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/sagaHelpers/index' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/sagaHelpers/takeEvery' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/sagaHelpers/takeLatest' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/sagaHelpers/throttle' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/scheduler' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga/dist/redux-saga.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga'>;
}
declare module 'redux-saga/dist/redux-saga.min.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga.min'>;
}
declare module 'redux-saga/es/effects.js' {
  declare module.exports: $Exports<'redux-saga/es/effects'>;
}
declare module 'redux-saga/es/index.js' {
  declare module.exports: $Exports<'redux-saga/es/index'>;
}
declare module 'redux-saga/es/internal/buffers.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/buffers'>;
}
declare module 'redux-saga/es/internal/channel.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/channel'>;
}
declare module 'redux-saga/es/internal/io.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/io'>;
}
declare module 'redux-saga/es/internal/middleware.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/middleware'>;
}
declare module 'redux-saga/es/internal/proc.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/proc'>;
}
declare module 'redux-saga/es/internal/runSaga.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/runSaga'>;
}
declare module 'redux-saga/es/internal/sagaHelpers/fsmIterator.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/sagaHelpers/fsmIterator'>;
}
declare module 'redux-saga/es/internal/sagaHelpers/index.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/sagaHelpers/index'>;
}
declare module 'redux-saga/es/internal/sagaHelpers/takeEvery.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/sagaHelpers/takeEvery'>;
}
declare module 'redux-saga/es/internal/sagaHelpers/takeLatest.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/sagaHelpers/takeLatest'>;
}
declare module 'redux-saga/es/internal/sagaHelpers/throttle.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/sagaHelpers/throttle'>;
}
declare module 'redux-saga/es/internal/scheduler.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/scheduler'>;
}
declare module 'redux-saga/es/internal/utils.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/utils'>;
}
declare module 'redux-saga/es/utils.js' {
  declare module.exports: $Exports<'redux-saga/es/utils'>;
}
declare module 'redux-saga/lib/effects.js' {
  declare module.exports: $Exports<'redux-saga/lib/effects'>;
}
declare module 'redux-saga/lib/index.js' {
  declare module.exports: $Exports<'redux-saga/lib/index'>;
}
declare module 'redux-saga/lib/internal/buffers.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/buffers'>;
}
declare module 'redux-saga/lib/internal/channel.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/channel'>;
}
declare module 'redux-saga/lib/internal/io.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/io'>;
}
declare module 'redux-saga/lib/internal/middleware.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/middleware'>;
}
declare module 'redux-saga/lib/internal/proc.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/proc'>;
}
declare module 'redux-saga/lib/internal/runSaga.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/runSaga'>;
}
declare module 'redux-saga/lib/internal/sagaHelpers/fsmIterator.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/sagaHelpers/fsmIterator'>;
}
declare module 'redux-saga/lib/internal/sagaHelpers/index.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/sagaHelpers/index'>;
}
declare module 'redux-saga/lib/internal/sagaHelpers/takeEvery.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/sagaHelpers/takeEvery'>;
}
declare module 'redux-saga/lib/internal/sagaHelpers/takeLatest.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/sagaHelpers/takeLatest'>;
}
declare module 'redux-saga/lib/internal/sagaHelpers/throttle.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/sagaHelpers/throttle'>;
}
declare module 'redux-saga/lib/internal/scheduler.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/scheduler'>;
}
declare module 'redux-saga/lib/internal/utils.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/utils'>;
}
declare module 'redux-saga/lib/utils.js' {
  declare module.exports: $Exports<'redux-saga/lib/utils'>;
}
declare module 'redux-saga/rollup.config.js' {
  declare module.exports: $Exports<'redux-saga/rollup.config'>;
}
declare module 'redux-saga/src/effects.js' {
  declare module.exports: $Exports<'redux-saga/src/effects'>;
}
declare module 'redux-saga/src/index.js' {
  declare module.exports: $Exports<'redux-saga/src/index'>;
}
declare module 'redux-saga/src/internal/buffers.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/buffers'>;
}
declare module 'redux-saga/src/internal/channel.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/channel'>;
}
declare module 'redux-saga/src/internal/io.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/io'>;
}
declare module 'redux-saga/src/internal/middleware.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/middleware'>;
}
declare module 'redux-saga/src/internal/proc.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/proc'>;
}
declare module 'redux-saga/src/internal/runSaga.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/runSaga'>;
}
declare module 'redux-saga/src/internal/sagaHelpers/fsmIterator.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/sagaHelpers/fsmIterator'>;
}
declare module 'redux-saga/src/internal/sagaHelpers/index.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/sagaHelpers/index'>;
}
declare module 'redux-saga/src/internal/sagaHelpers/takeEvery.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/sagaHelpers/takeEvery'>;
}
declare module 'redux-saga/src/internal/sagaHelpers/takeLatest.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/sagaHelpers/takeLatest'>;
}
declare module 'redux-saga/src/internal/sagaHelpers/throttle.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/sagaHelpers/throttle'>;
}
declare module 'redux-saga/src/internal/scheduler.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/scheduler'>;
}
declare module 'redux-saga/src/internal/utils.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/utils'>;
}
declare module 'redux-saga/src/utils.js' {
  declare module.exports: $Exports<'redux-saga/src/utils'>;
}
