// flow-typed signature: 182efbd3ada2d1314d4f8e0ed8182db0
// flow-typed version: <<STUB>>/redux-action_v^1.2.2/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-action'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-action' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-action/build/create-action' {
  declare module.exports: any;
}

declare module 'redux-action/build/create-reducer' {
  declare module.exports: any;
}

declare module 'redux-action/build/create-sync-action' {
  declare module.exports: any;
}

declare module 'redux-action/build/index' {
  declare module.exports: any;
}

declare module 'redux-action/build/util' {
  declare module.exports: any;
}

declare module 'redux-action/lib/create-action' {
  declare module.exports: any;
}

declare module 'redux-action/lib/create-reducer' {
  declare module.exports: any;
}

declare module 'redux-action/lib/create-sync-action' {
  declare module.exports: any;
}

declare module 'redux-action/lib/index' {
  declare module.exports: any;
}

declare module 'redux-action/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-action/build/create-action.js' {
  declare module.exports: $Exports<'redux-action/build/create-action'>;
}
declare module 'redux-action/build/create-reducer.js' {
  declare module.exports: $Exports<'redux-action/build/create-reducer'>;
}
declare module 'redux-action/build/create-sync-action.js' {
  declare module.exports: $Exports<'redux-action/build/create-sync-action'>;
}
declare module 'redux-action/build/index.js' {
  declare module.exports: $Exports<'redux-action/build/index'>;
}
declare module 'redux-action/build/util.js' {
  declare module.exports: $Exports<'redux-action/build/util'>;
}
declare module 'redux-action/lib/create-action.js' {
  declare module.exports: $Exports<'redux-action/lib/create-action'>;
}
declare module 'redux-action/lib/create-reducer.js' {
  declare module.exports: $Exports<'redux-action/lib/create-reducer'>;
}
declare module 'redux-action/lib/create-sync-action.js' {
  declare module.exports: $Exports<'redux-action/lib/create-sync-action'>;
}
declare module 'redux-action/lib/index.js' {
  declare module.exports: $Exports<'redux-action/lib/index'>;
}
declare module 'redux-action/lib/util.js' {
  declare module.exports: $Exports<'redux-action/lib/util'>;
}
