// flow-typed signature: 039fa36d8a7e5efd8e63ed4a72997511
// flow-typed version: <<STUB>>/socket.io_v^2.0.3/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socket.io/lib/client' {
  declare module.exports: any;
}

declare module 'socket.io/lib/index' {
  declare module.exports: any;
}

declare module 'socket.io/lib/namespace' {
  declare module.exports: any;
}

declare module 'socket.io/lib/socket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socket.io/lib/client.js' {
  declare module.exports: $Exports<'socket.io/lib/client'>;
}
declare module 'socket.io/lib/index.js' {
  declare module.exports: $Exports<'socket.io/lib/index'>;
}
declare module 'socket.io/lib/namespace.js' {
  declare module.exports: $Exports<'socket.io/lib/namespace'>;
}
declare module 'socket.io/lib/socket.js' {
  declare module.exports: $Exports<'socket.io/lib/socket'>;
}
