// flow-typed signature: b9083b11f1a96037c8cf7735a9feee50
// flow-typed version: <<STUB>>/webpack-notifier_v^1.5.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-notifier/index' {
  declare module.exports: $Exports<'webpack-notifier'>;
}
declare module 'webpack-notifier/index.js' {
  declare module.exports: $Exports<'webpack-notifier'>;
}
