export const container: string;
export const timeGrid: string;
export const timeThread: string;
export const rangeBar: string;
export const handle: string;
export const rangeFromHandle: string;
export const rangeToHandle: string;
export const tooltip: string;
export const active: string;
