export const bottomHeight: string;
export const container: string;
export const middle: string;
export const left: string;
export const seekBar: string;
export const right: string;
export const leftContent: string;
export const rightContent: string;
export const bottom: string;
