export const container: string;
export const timeGrid: string;
export const timeThread: string;
export const focusBar: string;
export const focusHandle: string;
export const leftFocusHandle: string;
export const rightFocusHandle: string;
export const tooltip: string;
export const active: string;
