// flow-typed signature: 4d7f4c22cf72593140b503121dc8fe07
// flow-typed version: <<STUB>>/@flow-atom/electron_v^0.37.8-rev.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@flow-atom/electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@flow-atom/electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@flow-atom/electron/sig/v0.37.8/app' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/autoUpdater' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$FontFamily' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$Options' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$TitleBarStyle' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$Type' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$WebPreferences' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/clipboard' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/contentTracing' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/crashReporter' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/dialog' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/globalShortcut' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/index' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/ipcMain' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/ipcRenderer' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/Menu' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/MenuItem' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/NativeImage' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/powerMonitor' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/powerSaveBlocker' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/protocol' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/remote' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/screen' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/session' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/shell' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/systemPreferences' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/ThumbBarButton' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/ThumbBarButtonFlags' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/Tray' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/WebContents' {
  declare module.exports: any;
}

declare module '@flow-atom/electron/sig/v0.37.8/webFrame' {
  declare module.exports: any;
}

// Filename aliases
declare module '@flow-atom/electron/sig/v0.37.8/app.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/app'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/autoUpdater.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/autoUpdater'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/BrowserWindow'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$FontFamily.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/BrowserWindow$FontFamily'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$Options.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/BrowserWindow$Options'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$TitleBarStyle.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/BrowserWindow$TitleBarStyle'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$Type.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/BrowserWindow$Type'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/BrowserWindow$WebPreferences.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/BrowserWindow$WebPreferences'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/clipboard.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/clipboard'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/contentTracing.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/contentTracing'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/crashReporter.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/crashReporter'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/dialog.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/dialog'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/globalShortcut.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/globalShortcut'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/index.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/index'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/ipcMain.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/ipcMain'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/ipcRenderer.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/ipcRenderer'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/Menu.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/Menu'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/MenuItem.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/MenuItem'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/NativeImage.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/NativeImage'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/powerMonitor.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/powerMonitor'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/powerSaveBlocker.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/powerSaveBlocker'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/protocol.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/protocol'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/remote.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/remote'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/screen.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/screen'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/session.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/session'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/shell.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/shell'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/systemPreferences.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/systemPreferences'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/ThumbBarButton.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/ThumbBarButton'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/ThumbBarButtonFlags.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/ThumbBarButtonFlags'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/Tray.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/Tray'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/WebContents.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/WebContents'>;
}
declare module '@flow-atom/electron/sig/v0.37.8/webFrame.js' {
  declare module.exports: $Exports<'@flow-atom/electron/sig/v0.37.8/webFrame'>;
}
