export const inputText: string;
export const inputContainer: string;
export const inputAppear: string;
export const input: string;
export const hint: string;
export const listContainer: string;
export const listAppear: string;
export const option: string;
export const isSelected: string;
