export const DESCRIPTOR_TYPE = {
  REF_TO_LOCAL_HIDDEN_VALUE: 'ReferenceToLocalHiddenValue',
  COMPONENT_INSTANTIATION_VALUE_DESCRIPTOR: 'ComponentInstantiationValueDescriptor',
}

export const NODE_TYPE = {
  COMPONENT: 'COMPONENT',
  TEXT: 'TEXT',
}

export const ACTION = {
  TYPE_SET: 'TYPE_SET',
  NODE_ADD: 'NODE_ADD',
  NODE_MOVE: 'NODE_MOVE',
  NODE_MOVE_CANCEL: 'NODE_MOVE_CANCEL',
  NODE_TEXT_CHANGE: 'NODE_TEXT_CHANGE',
  NODE_DELETE: 'NODE_DELETE',
  NODE_CLASS_SET: 'NODE_CLASS_SET',
}

export const STATUS = {
  UNCHANGED: 'UNCHANGED',
  CHANGED: 'CHANGED',
  RELOCATED: 'RELOCATED',
  RELOCATION_CANCELED: 'RELOCATION_CANCELED',
  INITIALIZED: 'INITIALIZED',
  UNINITIALIZED: 'UNINITIALIZED',
}

export const STATUS_BY_ACTION = {
  DEFAULT: STATUS.UNCHANGED,
  TYPE_SET: STATUS.CHANGED,
  NODE_ADD: STATUS.UNINITIALIZED,
  NODE_MOVE: STATUS.RELOCATED,
  NODE_MOVE_CANCEL: STATUS.RELOCATION_CANCELED,
  NODE_TEXT_CHANGE: STATUS.CHANGED,
}
