export const REF_TO_LOCAL_HIDDEN_VALUE = 'ReferenceToLocalHiddenValue'
export const COMPONENT_INSTANTIATION_VALUE_DESCRIPTOR = 'ComponentInstantiationValueDescriptor'
export const CHANGE_TYPE = 'CHANGE_TYPE'
export const CHILD_ADD = 'CHILD_ADD'
export const NODE_MOVE = 'NODE_MOVE'
export const NODE_MOVE_CANCEL = 'NODE_MOVE_CANCEL'
export const COMPONENT = 'COMPONENT'
export const TEXT = 'TEXT'
export const UNCHANGED = 'UNCHANGED'
export const CREATED = 'CREATED'
export const TYPE_CHANGED = 'TYPE_CHANGED'
export const RELOCATED = 'RELOCATED'
export const RELOCATION_CANCELED = 'RELOCATION_CANCELED'
export const STATUS = {
  DEFAULT: UNCHANGED,
  CHILD_ADD: CREATED,
  NODE_MOVE: RELOCATED,
  NODE_MOVE_CANCEL: RELOCATION_CANCELED,
  CHANGE_TYPE: TYPE_CHANGED,
}

/*
const STATUS = {
  UNCHANGED: 'UNCHANGED',
  CHANGED: 'CHANGED',
  RELOCATED: 'RELOCATED',
  RELOCATION_CANCELED: 'RELOCATION_CANCELED',
  INITIALIZED: 'INITIALIZED',
  UNINITIALIZED: 'UNINITIALIZED',
}
*/