export const container: string;
export const expand: string;
export const isRelocated: string;
export const drop: string;
export const isCollapsed: string;
export const collapse: string;
export const root: string;
export const hoverSensor: string;
export const child: string;
