export const container: string;
export const input: string;
export const isDisabled: string;
export const list: string;
export const listAppear: string;
export const willUnmount: string;
export const listDisappear: string;
export const option: string;
export const isSelected: string;
