export const container: string;
export const isABoxBeingDragged: string;
export const isMoving: string;
export const canBeMerged: string;
export const indicateMerge: string;
export const wrapper: string;
export const boxLegends: string;
export const boxView: string;
export const resizeHandle: string;
